Module1 task3
htmlacademy-nodejs/1041917-typoteka-3 pull request #3
Opened 2021-04-09 22:43 UTC by AntonVolyk

2021-04-11 09:37 UTC, dean992008 requested changes

2021-04-11 09:37 UTC, dean992008 commented on .gitignore
> +mock.json
Файл который генерируется называется `mocks.json` он сейчас не игнорируется.

2021-04-11 09:37 UTC, dean992008 commented on src/constants/index.js
> +const EXIT_CODE = {
Это перечисления, нужно использовать синтаксис именования перечислений. 
https://up.htmlacademy.ru/nodejs/3/criteries#b7

2021-04-11 09:37 UTC, dean992008 commented on src/service/cli/generate.js
> +const MAX_COUNT = {
Это тоже перечисление.

2021-04-11 09:37 UTC, dean992008 commented on src/service/cli/generate.js
> +        return 1;
Сейчас после генериции файла нет никакого сообщения, нужно добавить сообщение в случае успешной генерации и в случае ошибки. 
Также для вывода статуса нужно использовать process.exit(...)

2021-04-11 09:37 UTC, dean992008 commented on src/service/cli/version.js
> +    console.info(version);
Я бы написал здесь: `console.info(packageJson.version)`

2021-04-11 09:37 UTC, dean992008 commented
Также в эту ветку нужно подтянуть изменения с мастера, сейчас смержить не получиться из-за конфликта.

2021-04-12 17:18 UTC, AntonVolyk commented on src/service/cli/version.js
> +    console.info(version);
поправил

2021-04-12 17:18 UTC, AntonVolyk commented on src/service/cli/generate.js
> +        return 1;
поправил

2021-04-12 17:18 UTC, AntonVolyk commented on src/service/cli/generate.js
> +const MAX_COUNT = {
поправил

2021-04-12 17:18 UTC, AntonVolyk commented on src/constants/index.js
> +const EXIT_CODE = {
поправил

2021-04-12 17:18 UTC, AntonVolyk commented on .gitignore
> +mock.json
поправил

2021-04-18 08:38 UTC, merged